### ISSUE TITLE
Line plot bug: no line is being drawn between discrete points

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/web-eda#1519]
Requires UX discussion before implementation:

In SCORE S. mansoni study, I filtered the data so that `Village study arm `= `Arm 6: Gaining-shsh`

This results in having data at just the following timepoints:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/25450900/206065284-2e1e9f1f-f547-4d37-a144-f7fd967e7c8b.png">

When I make a line plot of this subset, plotting S. mansoni against study timepoint I get the following plot:

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/25450900/222212454-90146734-2e3a-4a27-9df8-af660a898286.png">

My issue with the line plot is that is is a series of discrete points instead of a line plot. It is appropriate for a line to be drawn connecting the markers at Year 1, Year 3, and Year 5 to see how prevalence of schisto goes down over the course of the study

**Comment by danicahelb** [comment]
Discussed in 12/12 EDA UX meeting. This is a BUG related to https://github.com/VEuPathDB/web-eda/issues/1411

Once the related bug is fixed, we would expect that a line gets drawn between the remaining data points. If that does not happen, then @moontrip please fix the bug in this ticket as well. Thanks!

**Comment by danicahelb** [comment]
@nkittur-uga now that the bug has been fixed, can you see if there is the expected gap in the line now?

**Comment by nkittur-uga** [comment]
I'm afraid I still don't see the line connecting the points. (Same example as above)
![Screenshot 2023-01-19 at 1 28 20 PM](https://user-images.githubusercontent.com/67710160/213529655-0a485a63-7380-4baf-8453-8d1522f21e33.png)

**Comment by danicahelb** [comment]
Hey @moontrip I think this ticket does NOT depend on implementation of https://github.com/VEuPathDB/web-eda/issues/1082

**Comment by moontrip** [comment]
@danicahelb Thank you for your confirmation 👍 Then it is almost ready for merging actually 😄 I will do that

**Comment by danicahelb** [comment]
Looks great, thanks @moontrip!


![Image](https://user-images.githubusercontent.com/25450900/223195009-8a9454ce-1c12-48b6-8d64-d1519c916cf1.png)

**Comment by moontrip** [comment]
@danicahelb Thank you for your reviews and tests. Glad it worked out 👍
