### ISSUE TITLE
Visualizations: Consistent styling of "no data" representations

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/web-eda#335]
In scatter, we use a gray 'x' which is a different marker entirely from the other points.

Currently, when a bar plot shows a 'no data' bar, it is styled just like the other bars but is gray in its (filled) color. To be more consistent with the scatter representation of no data and prevent accessibility issues, perhaps we should change the style of the 'no data' bar to a gray outline and empty fill, or a hashed fill.

Additionally, we should check that our choice for the 'no data' bar also generalizes to the other visualizations that will ever show no data. 

## To dos before implementation 
- [ ] Get a final list of all plot types that will ever represent 'no data'. (I'll do)
- [ ] Make mockups of different ways of styling 'no data' representations that could generalize across viz types. (I'll do)
- [ ] Get feedback and decide on strategy

**Comment by bobular** [comment]
Reviewing the implementation cost...

Our plot components library is only set up for providing a custom `color` in the data structure.  We would either have to add a new `fill` prop or pass a magic value to the `color` prop and then handle this somehow.  I prefer the former.

Because this has to be implemented for each plot component, it's more than low cost, but it's not a massive deal.

**Comment by asizemore** [comment]
Great thank you! I'll gather the list of vizs this affects today, make mockups tomorrow, share with you to make sure they're doable, and then ask for mockup review from the rest of the group.

**Comment by asizemore** [comment]
The below is the current suggestion for how to handle the no data visual representation across vizs. See slack thread for full discussion.
<img width="1357" alt="Screen Shot 2021-09-06 at 5 00 20 PM" src="https://user-images.githubusercontent.com/11710234/132260348-10657184-16c4-4dc0-81f4-8bd107c391d0.png">

**Comment by bobular** [comment]
Sadly, doing this the easy way in Plotly is ugly.
We wouldn't want black outlines for the other overlay, categories would we?

![image](https://user-images.githubusercontent.com/308639/133103028-3c1e2316-d2d2-4695-87b8-21621b91b386.png)

**Comment by bobular** [comment]
Though this is what it looks like with dark grey lines for everything
![image](https://user-images.githubusercontent.com/308639/133105106-7deb36c4-6172-40e2-85d3-2cbc1fc5accd.png)

![image](https://user-images.githubusercontent.com/308639/133105224-22fb9467-11b0-47e7-9a60-bc84427b1ba8.png)

**Comment by bobular** [comment]
Here's a histogram with more default bins
![image](https://user-images.githubusercontent.com/308639/133106110-191ee6f9-6dc1-4699-862f-d6e4b1b12472.png)
![image](https://user-images.githubusercontent.com/308639/133106457-c8cfb2a4-503d-44b4-9444-bd5423806dcb.png)
![image](https://user-images.githubusercontent.com/308639/133106520-5ef115d3-8713-417e-95d4-5cfde4bbbefd.png)

**Comment by bobular** [comment]
Another option for consideration
![image](https://user-images.githubusercontent.com/308639/133112673-c43fdd9f-41b5-46df-8ac7-e6b4145b71dd.png)
![image](https://user-images.githubusercontent.com/308639/133112692-e32b5080-5588-4ba2-b11f-0721bdfb7e27.png)

**Comment by bobular** [comment]
Same as above but with a lighter grey
![image](https://user-images.githubusercontent.com/308639/133129349-63790740-04ae-4dbc-a6d3-789b87b39f6d.png)

And something with wider bins
![image](https://user-images.githubusercontent.com/308639/133129169-6a299eac-40cf-439f-b6b0-0c8696200597.png)

**Comment by danicahelb** [comment]
Discussed in 9/13/2021 EDA WG meeting.

Everyone likes the solution using the light grey outlines for no data, this is a good compromise

**Comment by d-callan** [comment]
i dont love this, but i suppose can live w it.. histograms to me ideally should be able to support both reads of length of the individual bars, as well as the area of all bars of a particular overlay color. but i agree of the options here presented by bob the last one is far better than the first..

**Comment by bobular** [comment]
> i dont love this, but i suppose can live w it.. histograms to me ideally should be able to support both reads of length of the individual bars, as well as the area of all bars of a particular overlay color. but i agree of the options here presented by bob the last one is far better than the first..

Hi @d-callan - could you elaborate on how you think the user can't read the bar length or area of all bars of a particular overlay color?  Is it because of the white?

**Comment by d-callan** [comment]
It still supports bar length well, but area less so because of the white. It's workable though, and the least bad option of what I've seen.

**Comment by bobular** [comment]
@SheenaTomko  please resolve as required

**Comment by danicahelb** [comment]
Checked with WASHb Kenya, using `Bruising during last 7 days, caregiver report` as the overlay variable

Styling of "no data" for the overlay variable looks good for these visualizations: 
- Scatter plot
- Box plot
- Bar plot (because x-axis variable can only have 10 or fewer values, we don't see the issue noted for histograms, below)

**There are issues with these visualizations:**
- Histogram: when the bin width is narrow, the trace is obviously outside of the "no data" bar and looks strange
![image](https://user-images.githubusercontent.com/25450900/135361139-1593354d-262b-44cb-9449-cf9ab4b5bddc.png)

**Comment by bobular** [comment]
GEMS1A example

![image](https://user-images.githubusercontent.com/308639/135614177-89454f45-61d9-4719-af3a-ca14a6b4cfd4.png)

**Comment by bobular** [comment]
This is potentially fixed in https://github.com/VEuPathDB/web-components/pull/217 

It's in a different repo, so we'll have to close this manually.

**Comment by danicahelb** [comment]
@bobular this still doesn't look fixed to me, have the changes been pushed to the qa sites?
![image](https://user-images.githubusercontent.com/25450900/136065478-563769fc-00ad-48f9-8547-bd16940c078a.png)

**Comment by danicahelb** [comment]
looks good enough
![image](https://user-images.githubusercontent.com/25450900/136637730-6f7f6c5d-2610-4e31-9812-1e5d428d11ed.png)
